# Generated by Django 5.2.4 on 2025-09-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(unique=True)),
                ('company_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Datapoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analyst.companies')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analyst.dates')),
            ],
        ),
    ]
